#!/usr/bin/expect

set timeout 20
set password "1234"

# Upload server.js
spawn scp server.js root@212.90.120.135:/root/ecokambio/server.js
expect {
    "password:" {
        send "$password\r"
        exp_continue
    }
    eof
}

# Hard restart
spawn ssh root@212.90.120.135 "cd /root/ecokambio && pm2 delete all; pm2 start server.js --name ecokambio"
expect {
    "password:" {
        send "$password\r"
        exp_continue
    }
    eof
}
