require('dotenv').config();
const { createClient } = require('@supabase/supabase-js');
const axios = require('axios');

const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_KEY);

const BOOTSTRAP_API_URL = 'http://localhost:' + (process.env.PORT || 3000);

async function formatAndLog(label, data) {
    console.log(`\n=== ${label} ===`);
    console.dir(data, { depth: null, colors: true });
}

async function runTest() {
    try {
        console.log('🚀 Starting AppyPay Integration Test...');
        console.log('Target URL:', BOOTSTRAP_API_URL);

        // 1. Create a Test User
        const phone = '999999999';
        console.log(`\n1. Creating/Fetching User (${phone})...`);
        let { data: user } = await supabase.from('ecoflix_users').select('*').eq('phone', phone).single();

        if (!user) {
            const { data: newUser, error } = await supabase.from('ecoflix_users').insert({ phone, verified_at: new Date() }).select().single();
            if (error) throw error;
            user = newUser;
        }
        console.log('User ID:', user.id);

        // 2. Create a Mock Order directly in DB (to simulate pending state)
        const refId = `TEST_${Date.now()}`;
        const txnId = `TXN_${Date.now()}`;
        console.log(`\n2. Creating Pending Order (Ref: ${refId})...`);

        const { data: order, error: orderError } = await supabase
            .from('ecoflix_orders')
            .insert({
                user_id: user.id,
                reference_id: refId, // Normally generated by AppyPay
                entity: '90000',
                plan_type: 'ECONOMICO',
                amount: 4500,
                status: 'PENDING',
                phone: phone
            })
            .select()
            .single();

        if (orderError) throw orderError;
        console.log('Order Created:', order.id);

        // 3. Simulate AppyPay Webhook
        console.log('\n3. Sending Webhook Request...');
        const webhookPayload = {
            reference: refId,
            block: false, // AppyPay specific
            amount: 4500,
            transaction_id: txnId,
            status: 'paid', // or 'success'
            date: new Date().toISOString()
        };

        try {
            const res = await axios.post(`${BOOTSTRAP_API_URL}/api/ecoflix/webhooks/appypay`, webhookPayload);
            console.log('Webhook Response:', res.data);
            if (!res.data.success) throw new Error('Webhook returned false success');
        } catch (webhookError) {
            console.error('Webhook Call Failed:', webhookError.message);
            if (webhookError.response) {
                console.error('Status:', webhookError.response.status);
                console.error('Data:', webhookError.response.data);
            }
            throw webhookError;
        }

        // 4. Verify Order Status
        console.log('\n4. Verifying Order Status...');
        const { data: updatedOrder } = await supabase
            .from('ecoflix_orders')
            .select('*')
            .eq('id', order.id)
            .single();

        console.log('Updated Status:', updatedOrder.status);
        console.log('Transaction ID:', updatedOrder.transaction_id);

        if (updatedOrder.status !== 'PAID' && updatedOrder.status !== 'PAID_NO_STOCK') {
            throw new Error(`Order status mismatch! Expected PAID/PAID_NO_STOCK, got ${updatedOrder.status}`);
        }

        if (updatedOrder.transaction_id !== txnId) {
            console.warn('Warning: Transaction ID was not updated!');
        }

        console.log('\n✅ TEST PASSED!');

    } catch (error) {
        console.error('\n❌ TEST FAILED:', error.message);
        process.exit(1);
    }
}

runTest();
